### ISSUE TITLE
Make sure our use of Intl works on IE11

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#147]
In #143 I started using [`Intl`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) but I'm not sure if it works in IE11.

**Comment by toolness** [comment]
Alas, IE11 does support `Intl` but it doesn't support any timezone other than UTC:

```
RangeError: Option value 'AMERICA/NEW_YORK' for 'timeZone' is outside of valid range. Expected: ['UTC']
   at LetterStatus (http://localhost:8000/static/frontend/letter-of-complaint.bundle.js:582:9)
   at mountIndeterminateComponent (http://localhost:8000/static/frontend/main.bundle.js:29738:5)
   at beginWork (http://localhost:8000/static/frontend/main.bundle.js:30178:7)
   at performUnitOfWork (http://localhost:8000/static/frontend/main.bundle.js:32221:5)
   at workLoop (http://localhost:8000/static/frontend/main.bundle.js:32260:7)
   at renderRoot (http://localhost:8000/static/frontend/main.bundle.js:32300:7)
   at performWorkOnRoot (http://localhost:8000/static/frontend/main.bundle.js:32918:7)
   at performWork (http://localhost:8000/static/frontend/main.bundle.js:32840:7)
   at performSyncWork (http://localhost:8000/static/frontend/main.bundle.js:32812:3)
   at requestWork (http://localhost:8000/static/frontend/main.bundle.js:32712:5)
```

**Comment by toolness** [comment]
So I tried fiddling with this a bit and one option is to just remove the `timeZone` specifier entirely, which makes the JS engine use whatever the local time zone is.  However, this results in a weird flicker on page load if the server has a different time zone than the browser (this actually seems to be the case on my local dev machine, I think the server thinks local time is UTC, while the browser thinks it's EST).

One option might be to just force the time zone to `UTC`, which all browsers that implement `Intl` support, but this results in confusing output, because the date may very likely be in the future.
