### ISSUE TITLE
HP Action webhook sometimes doesn't include payload

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#700]
Sometimes LHI pings us back but doesn't include the PDF in the payload, which causes us to 500 and then tell the user that something went wrong while generating the HP action documents.

This happened today but I think I've seen it happen before.  We might want to log the contents of such requests and/or ask LHI about what's going on with them.

```
2019-06-25T18:39:00.011898+00:00 app[web.1]: Internal Server Error: /hp/upload/zVYxUXTNyZ2bYRIVOAAHPxqRFX7tppikqX6e9i2N
2019-06-25T18:39:00.011914+00:00 app[web.1]: Traceback (most recent call last):
2019-06-25T18:39:00.011918+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
2019-06-25T18:39:00.011920+00:00 app[web.1]: list_ = super().__getitem__(key)
2019-06-25T18:39:00.011923+00:00 app[web.1]: KeyError: 'binary_file'
2019-06-25T18:39:00.011925+00:00 app[web.1]:
2019-06-25T18:39:00.011927+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2019-06-25T18:39:00.011929+00:00 app[web.1]:
2019-06-25T18:39:00.011932+00:00 app[web.1]: Traceback (most recent call last):
2019-06-25T18:39:00.011934+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2019-06-25T18:39:00.011936+00:00 app[web.1]: response = get_response(request)
2019-06-25T18:39:00.011938+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
2019-06-25T18:39:00.011941+00:00 app[web.1]: response = self.process_exception_by_middleware(e, request)
2019-06-25T18:39:00.011943+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
2019-06-25T18:39:00.011946+00:00 app[web.1]: response = wrapped_callback(request, *callback_args, **callback_kwargs)
2019-06-25T18:39:00.011948+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
2019-06-25T18:39:00.011950+00:00 app[web.1]: return view_func(*args, **kwargs)
2019-06-25T18:39:00.011952+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner
2019-06-25T18:39:00.011954+00:00 app[web.1]: return func(request, *args, **kwargs)
2019-06-25T18:39:00.011956+00:00 app[web.1]: File "/tenants2/hpaction/views.py", line 41, in upload
2019-06-25T18:39:00.011959+00:00 app[web.1]: pdf_data = decode_lhi_b64_data(request.POST['binary_file'])
2019-06-25T18:39:00.011961+00:00 app[web.1]: File "/usr/local/lib/python3.7/site-packages/django/utils/datastructures.py", line 80, in __getitem__
2019-06-25T18:39:00.011963+00:00 app[web.1]: raise MultiValueDictKeyError(key)
2019-06-25T18:39:00.011965+00:00 app[web.1]: django.utils.datastructures.MultiValueDictKeyError: 'binary_file'
2019-06-25T18:39:00.192016+00:00 app[web.1]: Received unexpected response from GetAnswersAndDocuments(): The remote server returned an error: (500) Internal Server Error.
```

**Comment by toolness** [comment]
On or after March 1, LHI started sending POSTs with no data in them, raising this exact exception.  I've started logging the POST bodies in #1017 and we're now responding with a 400 instead of a 500, but as far as I can tell, this appears to be a problem on LHI's end, not ours.

**Comment by toolness** [comment]
Note that the above issue was fixed by LHI a shortly after we reported it (it was due to some kind of system migration that broke our endpoint) but it's happening again reliably this morning.

We might want to make some kind of command that tests the integration to make sure it works, and alerts us and LHI if it doesn't.
